extern const GeoLayout moon_geo[];
extern Lights1 moon_Body_003_f3d_lights;
extern u8 moon_body_rgba16[];
extern u8 moon_eye_rgba16[];
extern Vtx moon_000_displaylist_mesh_layer_1_vtx_0[36];
extern Gfx moon_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx moon_001_displaylist_mesh_layer_4_vtx_0[8];
extern Gfx moon_001_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_moon_Body_003_f3d[];
extern Gfx mat_moon_Eyes_003_f3d[];
extern Gfx mat_revert_moon_Eyes_003_f3d[];
extern Gfx moon_000_displaylist_mesh_layer_1[];
extern Gfx moon_001_displaylist_mesh_layer_4[];
extern Gfx moon_material_revert_render_settings[];
